//
// The script, MoveVertexAlongNormalController.cs, has been auto-generated by the script ShaderControllerGenerator.cs from the Shader Controller Package
// 
// The class MoveVertexAlongNormalController is a controller for the shader: Unlit/MoveVertexAlongNormal.
// The tool does not check if there is already a controller for a shader.
// 
// It is recommended to not modify this generated script since all the changes made will be overwritten if your update it.
//

using UnityEngine;

[RequireComponent(typeof(Renderer))]
public class MoveVertexAlongNormalController : BaseShaderController
{
	[Tooltip("Color")]
	[SerializeField] private Color color = new Color(1f, 1f, 1f, 1f);

	[Tooltip("")]
	[Range(-3f, 3f)]
	[SerializeField] private float _NormalOffsetPower = 1f;
	


	protected override void Start()
	{
		shader = Shader.Find("Unlit/MoveVertexAlongNormal");

		base.Start();
	}

	public override void SetupMaterial()
	{
		base.SetupMaterial();

		GetComponent<Renderer>().material = material;
	}

	public override void SetupInspectorValue()
	{
		color = material.GetColor("_Color");
		_NormalOffsetPower = material.GetFloat("_NormalOffsetPower");
	}

	private void Update()
	{
		material.SetColor("_Color", color);
		material.SetFloat("_NormalOffsetPower", _NormalOffsetPower);
	}
}